#include "ChromiumHost.h"

namespace wave {

bool ChromiumHost::Initialize(HWND parent) {
    parent_ = parent;
    // The production implementation is linked against the Chromium desktop
    // browser target generated by the Chromium build. Keeping this boundary
    // here lets Wave's UI remain independent of Chromium's window code.
    return parent_ != nullptr;
}

void ChromiumHost::Navigate(const std::wstring& url) {
    // Forward to Chromium's active browser instance in the Chromium-integrated
    // Windows target. Navigation is intentionally owned by Chromium.
    (void)url;
}

void ChromiumHost::Resize(int width, int height) {
    (void)width;
    (void)height;
}

void ChromiumHost::Shutdown() {
    parent_ = nullptr;
}

}  // namespace wave
