#pragma once

#include "plugin_config.h"
#include "tv_remotes/tv_remote.h"
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

// Aroma plugin install path
#define AROMA_PLUGIN_DIR  "fs:/vol/external01/wiiu/environments/aroma/plugins"
#define PLUGIN_INSTALL_PATH \
    "fs:/vol/external01/wiiu/environments/aroma/plugins/WaveBrowserRemote.wps"

// Embedded .wps binary — generated by build.yml into plugin_data.h
// Falls back gracefully if not available (first build before plugin is compiled)
#if __has_include("plugin_data.h")
#  include "plugin_data.h"
#  define HAVE_PLUGIN_BINARY 1
#else
#  define HAVE_PLUGIN_BINARY 0
#endif

// ─── Write plugin config file ─────────────────────────────────────────────────
// Called by settings.cpp whenever the user selects / changes a TV model.
// The Aroma plugin reads this file on every TV button press.

static inline bool plugin_write_config(const TVRemoteModel* m)
{
    if (!m) return false;

    TVPluginConfig cfg = {};
    cfg.magic   = PLUGIN_CONFIG_MAGIC;
    cfg.version = PLUGIN_CONFIG_VERSION;
    cfg.year    = (uint16_t)m->year;

    // Copy brand / model strings safely
    strncpy(cfg.brand, m->brand, sizeof(cfg.brand)-1);
    strncpy(cfg.model, m->model, sizeof(cfg.model)-1);

    // Map IRProtocol enum → PROTO_* constants
    switch (m->protocol) {
        case IRProtocol::NEC:       cfg.protocol = PROTO_NEC;       break;
        case IRProtocol::SAMSUNG:   cfg.protocol = PROTO_SAMSUNG;   break;
        case IRProtocol::SIRCS_12:  cfg.protocol = PROTO_SIRCS_12;  break;
        case IRProtocol::SIRCS_15:  cfg.protocol = PROTO_SIRCS_15;  break;
        case IRProtocol::SIRCS_20:  cfg.protocol = PROTO_SIRCS_20;  break;
        case IRProtocol::RC5:       cfg.protocol = PROTO_RC5;       break;
        case IRProtocol::RC6:       cfg.protocol = PROTO_RC6;       break;
        case IRProtocol::PANASONIC: cfg.protocol = PROTO_PANASONIC; break;
        case IRProtocol::JVC:       cfg.protocol = PROTO_JVC;       break;
        case IRProtocol::ROKU:      cfg.protocol = PROTO_ROKU;      break;
        default:                    cfg.protocol = PROTO_NONE;      break;
    }

    // Copy the top 7 IR slots
    static const TVBtn SLOTS[SLOT_COUNT] = {
        TVBTN_POWER, TVBTN_INPUT, TVBTN_MUTE,
        TVBTN_VOL_UP, TVBTN_VOL_DOWN, TVBTN_CH_UP, TVBTN_CH_DOWN
    };
    for (int i = 0; i < SLOT_COUNT; i++) {
        cfg.ir[i].code    = m->ir[SLOTS[i]].code;
        cfg.ir[i].repeats = m->ir[SLOTS[i]].repeats;
    }

    FILE* f = fopen(PLUGIN_CONFIG_PATH, "wb");
    if (!f) return false;
    bool ok = (fwrite(&cfg, 1, sizeof(cfg), f) == sizeof(cfg));
    fclose(f);
    return ok;
}

// ─── Auto-install plugin .wps to Aroma plugins directory ─────────────────────
// Returns:
//   0 = already up to date
//   1 = installed / updated successfully
//  -1 = failed (Aroma dir not found — user may not have Aroma)
//  -2 = no embedded binary (plugin not compiled yet)

static inline int plugin_install()
{
#if !HAVE_PLUGIN_BINARY
    return -2;
#else
    // Check Aroma directory exists
    struct stat st;
    if (stat(AROMA_PLUGIN_DIR, &st) != 0 || !S_ISDIR(st.st_mode))
        return -1;

    // Check if already installed with same size (simple version check)
    if (stat(PLUGIN_INSTALL_PATH, &st) == 0 &&
        (size_t)st.st_size == plugin_wps_len)
        return 0;   // already current

    // Write embedded .wps to SD
    FILE* f = fopen(PLUGIN_INSTALL_PATH, "wb");
    if (!f) return -1;
    bool ok = (fwrite(plugin_wps_data, 1, plugin_wps_len, f) == plugin_wps_len);
    fclose(f);
    return ok ? 1 : -1;
#endif
}
